filter:
    paths: [src/*]
    excluded_paths: [vendor/*, bin/*, bin/*]
tools:
    php_sim:
        enabled: true
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    external_code_coverage: true