language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

install:
    - composer install --prefer-dist --dev

before_script:
    - "mkdir -p ~/.composer"
    - cp .travis.composer.config.json ~/.composer/config.json

script:
    - ant -keep-going