services:
  form_helper.helper:
    class: Netzmacht\Contao\FormHelper\Helper
    arguments:
      - "@event_dispatcher"
      - "@form_helper.form_locator"

  form_helper.form_locator:
    class: Netzmacht\Contao\FormHelper\Form\FormLocator

  form_helper.listener.wrapper_css_classes_listener:
    class: Netzmacht\Contao\FormHelper\EventListener\WrapperCssClassesListener
    tags:
      - { name: kernel.event_listener, event: form_helper.create_view, method: onCreateView}
